export const registerTypes = {
    SET_FULLNAME_REGISTER: 'SET_FULLNAME_REGISTER',
    SET_USERNAME_REGISTER: 'SET_USERNAME_REGISTER',
    SET_PASSWORD_REGISTER: 'SET_PASSWORD_REGISTER',
    SET_CONFIRM_REGISTER:'SET_CONFIRM_REGISTER',
    RESET_INPUT: 'RESET_INPUT',
    SET_ISVALID_FULLNAME: 'ISVALID_FULLNAME',
    SET_ISVALID_USERNAME: 'ISVALID_USERNAME',
    SET_ISVALID_PASSWORD: 'ISVALID_PASSWORD',
    SET_ISVALID_COFIRM: 'ISVALID_COFIRM',
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    RESET_ISVALID: 'RESET_ISVALID',
    REGISTER_POST:'REGISTER_POST',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    RESET_REGISTER: 'RESET_REGISTER',
}

export const loginTypes = {
    SET_USERNAME_LOGIN: 'SET_USERNAME_LOGIN',
    SET_PASSWORD_LOGIN: 'SET_PASSWORD_LOGIN',
    RESET_INPUT_LOGIN: 'RESET_INPUT_LOGIN',
    SET_NOTIFICATION_LOGIN: 'SET_NOTIFICATION_LOGIN',
    LOGIN_POST: 'LOGIN_POST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    RESET_SUBMITFORM_LOGIN: 'RESET_SUBMITFORM_LOGIN',
}

export const blockChaninInforTypes ={
    SET_TRANSACTION: 'SET_TRANSACTION',
    TRANSACTION_POST: 'TRANSACTION_POST',
    TRANSACTION_FAIL: 'TRANSACTION_FAIL',
    TRANSACTION_SUCCESS: 'TRANSACTION_SUCCESS',
}

export const profileTypes = {
    SET_NAME_PROFILE: 'SET_NAME_PROFILE',
    SET_BALANCE: 'SET_BALANCE',
    SET_IDWALLET: 'SET_IDWALLET',
    SET_USERNAME_PROFILE: 'SET_USERNAME_PROFILE',
    SET_MYID: 'SET_MYID',
    POST_PROFILE: 'POST_PROFILE',
    GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS'
}