export const registerTypes = {
    SET_FULLNAME: 'SET_FULLNAME',
    SET_USERNAME: 'SET_USERNAME',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_CONFIRM:'SET_CONFIRM',
    SET_ISVALID_FULLNAME: 'ISVALID_FULLNAME',
    SET_ISVALID_USERNAME: 'ISVALID_USERNAME',
    SET_ISVALID_PASSWORD: 'ISVALID_PASSWORD',
    SET_ISVALID_COFIRM: 'ISVALID_COFIRM',
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    REGISTER_POST:'REGISTER_POST',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_RECEIVE: 'REGISTER_RECEIVE'
}