export const registerTypes = {
    SET_FULLNAME_REGISTER: 'SET_FULLNAME_REGISTER',
    SET_USERNAME_REGISTER: 'SET_USERNAME_REGISTER',
    SET_PASSWORD_REGISTER: 'SET_PASSWORD_REGISTER',
    SET_CONFIRM_REGISTER:'SET_CONFIRM_REGISTER',
    RESET_INPUT: 'RESET_INPUT',
    SET_ISVALID_FULLNAME: 'ISVALID_FULLNAME',
    SET_ISVALID_USERNAME: 'ISVALID_USERNAME',
    SET_ISVALID_PASSWORD: 'ISVALID_PASSWORD',
    SET_ISVALID_COFIRM: 'ISVALID_COFIRM',
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    RESET_ISVALID: 'RESET_ISVALID',
    REGISTER_POST:'REGISTER_POST',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    RESET_REGISTER: 'RESET_REGISTER',
}

export const loginTypes = {
    SET_USERNAME_LOGIN: 'SET_USERNAME_LOGIN',
    SET_PASSWORD_LOGIN: 'SET_PASSWORD_LOGIN',
    RESET_INPUT_LOGIN: 'RESET_INPUT_LOGIN',
    SET_NOTIFICATION_LOGIN: 'SET_NOTIFICATION_LOGIN',
    LOGIN_POST: 'LOGIN_POST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    RESET_SUBMITFORM_LOGIN: 'RESET_SUBMITFORM_LOGIN',
}

export const blockChaninInforTypes ={
    SET_TRANSACTION: 'SET_TRANSACTION',
    TRANSACTION_POST: 'TRANSACTION_POST',
    TRANSACTION_FAIL: 'TRANSACTION_FAIL',
    TRANSACTION_SUCCESS: 'TRANSACTION_SUCCESS',
}

export const profileTypes = {
    SET_NAME_PROFILE: 'SET_NAME_PROFILE',
    SET_BALANCE: 'SET_BALANCE',
    SET_IDWALLET: 'SET_IDWALLET',
    SET_USERNAME_PROFILE: 'SET_USERNAME_PROFILE',
    SET_MYID: 'SET_MYID',
    POST_PROFILE: 'POST_PROFILE',
    GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',

    POST_TRANSACTION_PROFILE: 'POST_TRANSACTION_PROFILE',
    GET_TRANSACTION_FAIL: 'GET_TRANSACTION_FAIL',
    GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
    SET_TRANSACTION_PROFILE: 'SET_TRANSACTION_PROFILE',

    OPEN_DIALOG_SENT: 'OPEN_DIALOG_SENT',
    CLOSE_DIALOG_SENT: 'CLOSE_DIALOG_SENT',
    SET_IDWALLET_SENT: 'SET_IDWALLET_SENT',
    SET_AMOUNT_SENT: 'SET_AMOUNT_SENT',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_MYID_SENT: 'SET_MYID_SENT',
    RESET_INPUT_SENT: 'RESET_INPUT_SENT',
    SET_ISVALID_IDWALLET_SENT:'SET_ISVALID_IDWALLET_SENT',
    SET_ISVALID_AMOUNT_SENT: 'SET_ISVALID_AMOUNT_SENT',
    SET_ISVALID_DESCRIPTION: 'SET_ISVALID_DESCRIPTION',
    SET_ISVALID_FORM_SENT: 'SET_ISVALID_FORM_SENT',
    RESET_ISVALID_SENT: 'RESET_ISVALID_SENT',
    POST_SENT:'POST_SENT',
    SENT_FAIL: 'SENT_FAIL',
    SENT_SUCCESS: 'SENT_SUCCESS',
    RESET_SUBMIT_FORM_SENT: 'RESET_SUBMIT_FORM_SENT'

}